---
title: "Draft Quarto document"
author: "Asger A. Bech"
format: html
---

## Header 1

```{r setup}
library(tidyverse)
library(here)
library(snakecase)
```


## Importing new data
```{r}
here("data-raw/nurses-stress/stress/5C/5C_1586886626/HR.csv.gz") |>
  read_csv(
    show_col_types = FALSE,
    name_repair = to_snake_case,
    n_max = 100
  )
```

## Exercise Reading other files
```{r}
here("data-raw/nurses-stress/stress/5C/5C_1586886712/HR.csv.gz") |>
  read_csv(
    show_col_types = FALSE,
    name_repair = to_snake_case,
    n_max = 100
  )
```

```{r}
here("data-raw/nurses-stress/stress/6B/6B_1587569373/HR.csv.gz") |>
  read_csv(
    show_col_types = FALSE,
    name_repair = to_snake_case,
    n_max = 100
  )
```

## Creating a function
```{r}
#' Add two numbers together
#'
#' @param num1 A number here.
#' @param num2 A number here.
#'
#' @returns Returns the sum of two numbers.
#'
add_numbers <- function(num1, num2) {
  added <- num1 + num2
  return(added)
}
```

## Creating a function to import data
```{r}
#' Read in one nurses' stress data file.
#'
#' @param file_path A path to a data file
#' @param max_rows Number of rows in output
#'
#' @returns Outputs a data frame / tibble
read <- function(file_path, max_rows = 100) {
  data <- file_path |>
    readr::read_csv(
      show_col_types = FALSE,
      name_repair = snakecase::to_snake_case,
      n_max = max_rows
    )
  return(data)
}
```

```{r}
here("data-raw/nurses-stress/stress/5C/5C_1586886626/HR.csv.gz") |>
  read()
```

```{r}
here("data-raw/nurses-stress/stress/5C/5C_1586886712/HR.csv.gz") |>
  read()
```

```{r}
here("data-raw/nurses-stress/stress/5C/5C_1586886712/HR.csv.gz") |>
  read(max_rows = 1000)
```

```{r}
here("data-raw/nurses-stress/stress/5C/5C_1586886712/HR.csv.gz") |>
  read(max_rows = Inf)
```
